# Generated by Django 5.2.9 on 2026-02-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tag_todo_due_date_todo_is_archived_todo_is_pinned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_pinned',
        ),
    ]
