# Generated by Django 5.2.9 on 2026-03-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.IntegerField(choices=[(1, 'light'), (2, 'dark')], default=1),
        ),
    ]
