"""
Django settings for todo_project project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
# below code is for SECRET_KEY Fallback
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# fetch the SECRET_KEY and DEBUG form .env 
load_dotenv(BASE_DIR / ".env")

from django.core.exceptions import ImproperlyConfigured

DEBUG = os.getenv("DEBUG", "True") == "True"

_secret_key_env = os.getenv("SECRET_KEY")

if _secret_key_env:
    SECRET_KEY = _secret_key_env
elif DEBUG:
    SECRET_KEY = get_random_secret_key()
else:
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable is missing. "
        "This must be set in production (DEBUG=False)."
    )

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost"
).split(",")


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # 'rest_framework_simplejwt',
    'accounts',
    'todo',
    # token auth based login 
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise must be placed immediately after SecurityMiddleware so it can
    # serve static files efficiently before the request reaches Django views.
    # https://whitenoise.readthedocs.io/en/stable/django.html
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'todo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'todo_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Local development (DATABASE_URL not set):
#   Uses SQLite — no setup required, works immediately after cloning.
#
# Production (DATABASE_URL set, e.g. on Render with Neon PostgreSQL):
#   dj-database-url parses the full connection string and configures
#   Django to use PostgreSQL automatically. The Neon connection string
#   format is: postgresql://user:password@host/dbname?sslmode=require
#
#   CONN_MAX_AGE=600 keeps connections alive for up to 10 minutes.
#   This is important for Neon Free tier, which closes idle connections
#   after ~5 minutes — without it Django would hit connection errors
#   on the next request after an idle period.

import dj_database_url

_database_url = os.getenv("DATABASE_URL", "")

if _database_url:
    DATABASES = {
        "default": dj_database_url.parse(
            _database_url,
            conn_max_age=600,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# STATIC_ROOT is the directory where collectstatic gathers all static files
# for production serving. WhiteNoise serves files from this directory.
# The 'staticfiles/' directory is already listed in .gitignore.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

# Before auth token change code i.e original JWT based
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     )
# }


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# CORS Configuration
# ---------------------------------------------------------------
# Development (DEBUG=True): allow all origins for convenience so
#   the local React dev server works without any extra config.
#
# Production (DEBUG=False): CORS_ALLOW_ALL_ORIGINS is disabled.
#   Set CORS_ALLOWED_ORIGINS in the environment to a comma-separated
#   list of the exact frontend origins that should be permitted.
#   Example: CORS_ALLOWED_ORIGINS=https://your-app.vercel.app
#
# If CORS_ALLOWED_ORIGINS is not set in production the API will
# reject cross-origin requests, which is the safe default.
# ---------------------------------------------------------------

_cors_origins_env = os.getenv("CORS_ALLOWED_ORIGINS", "").strip()

if DEBUG:
    # Local development: allow all origins so the React dev server works
    # without any extra configuration.
    CORS_ALLOW_ALL_ORIGINS = True
elif _cors_origins_env:
    # Production with origins configured: restrict to the supplied list only.
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        origin.strip()
        for origin in _cors_origins_env.split(",")
        if origin.strip()
    ]
else:
    # Production with CORS_ALLOWED_ORIGINS missing or empty: lock down.
    # Cross-origin requests are rejected. This is the safe production default.
    CORS_ALLOW_ALL_ORIGINS = False

# ---------------------------------------------------------------
# Production Security Settings (HTTPS / SSL / Cookies)
# ---------------------------------------------------------------
if not DEBUG:
    # Render terminates SSL at the load balancer and passes the X-Forwarded-Proto header.
    # This tells Django that the request was actually secure, preventing infinite redirect loops.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Redirect all HTTP traffic to HTTPS (though Render does this automatically, this is defense in depth)
    SECURE_SSL_REDIRECT = True

    # Ensure cookies are only sent over HTTPS (protects Django Admin sessions and CSRF tokens)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HTTP Strict Transport Security (HSTS)
    # Instructs browsers to ONLY connect via HTTPS for the specified time (1 year).
    # SECURE_HSTS_SECONDS = 31536000
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD = True
    # Note: HSTS is commented out because it requires careful testing in production.
    # If a subdomain doesn't have SSL, HSTS can break it. It's recommended but not forced here.
